drop table stage;
drop table entreprise;
drop table etudiant;
drop type stage_ty;
drop type entreprise_ty;
drop type etudiant_ty;
drop type adresse_ty;
drop type package types;
drop type ImbriStatTa;
drop type ImbriStatOb;
drop table statistics;